### PR TITLE
Working db connection

### PR DESCRIPTION
**Pull request by Lubbree**
yes it does delete everything time the app is started up, we can decide if that is a bug worth addressing.
**NEED TEST CONTAINERS** tests will not pass until that is done

### CODE REVIEW

**Review by EvanB213 — APPROVED** [review]
Testing should not matter until TestContainers implemented, dependencies look good

**Comment by EvanB213** [comment]
Added some front-end features and default products, needed more work before demo

**Comment by MatthewKhoury** [comment]
This looks great thank you evan.

**Comment by Lubbree** [comment]
Unfortunately, we had to remove the integration tests, they will be added in a further pull request.

**Review by bellaville — APPROVED** [review]
Looks good to merge

**Pull request merged**
