### PR TITLE
added home page, product controller, and product repostitory

### PR DESCRIPTION
**Pull request by Lubbree**
User -> Costumer: Needed to be done bc User is a protected term in H2

### CODE REVIEW

**Review by EvanB213 — COMMENTED** [review]
Costumer? replace with customer and good to merge

**Comment by bellaville** [comment]
I agree with Evan. Other than the spelling refactoring for Costumer everything else looks good.

**Review by bellaville — CHANGES_REQUESTED** [review]
Just need to replace "Costumer" with "Customer"

**Review by EvanB213 — APPROVED** [review]
Good for merge

**Review by bellaville — APPROVED** [review]
Looks good

**Comment by MatthewKhoury** [comment]
I agree with previous comments it should be good for integration

**Pull request merged**
